### ISSUE TITLE
Package doesn't load on Windows with python 3

### ISSUE THREAD

**Issue by deathaxe** [wvlia5/SublimeDebugger#14]
Upon ST startup the following exception is printed in console.

I guess as python2 is the default the `python2` command is tried to be executed.

I am running on Win 10 x64 with only python 3 installed, which is accessed by `python` or `py` via command line.

Could you add a check for availability of python2 and just disable it if it is not?

```
reloading plugin Python Debugger.mydebugger
Traceback (most recent call last):
  File "./python3.3/subprocess.py", line 1104, in _execute_child
FileNotFoundError: [WinError 2] Das System kann die angegebene Datei nicht finden

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Apps\Sublime\sublime_plugin.py", line 109, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "C:\Apps\Sublime\sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "mydebugger in C:\Apps\Sublime\Data\Installed Packages\Python Debugger.sublime-package", line 14, in <module>
  File "backends.dbPython2 in C:\Apps\Sublime\Data\Installed Packages\Python Debugger.sublime-package", line 9, in __init__
  File "./python3.3/subprocess.py", line 819, in __init__
  File "./python3.3/subprocess.py", line 1110, in _execute_child
FileNotFoundError: [WinError 2] Das System kann die angegebene Datei nicht finden
```

**Comment by matiasmorant** [comment]
Thanks for letting me know. I will

**Comment by deathaxe** [comment]
Btw.: Cool frontend/backend approach. Would really be cool to see other languages supporting that API.

**Comment by matiasmorant** [comment]
Thanks ;) Microsoft stole my idea for LSP, they haven't included debugging though

**Comment by matiasmorant** [comment]
Solved
