### ISSUE TITLE
Can't switch to Python2

### ISSUE THREAD

**Issue by Carbon401** [wvlia5/SublimeDebugger#26]
That's what I get after trying to switch to Python2.
```
Python2 not installed
Exception AttributeError: "'DBPython2' object has no attribute 'sp'" in <bound method DBPython2.__del__ of <Python Debugger.backends.dbPython2.DBPython2 object at 0x10dd27550>> ignored
```

**Comment by matiasmorant** [comment]
Python 2 is not installed in your system. You need to be able to run ```python2``` on a terminal for it to work properly

**Comment by Carbon401** [comment]
Well, I have Python 2.7.10 but python2 says command not found. My binaries are python and python2.7. The system won't let me create a /usr/bin/python2 symlink to /usr/bin/python even with sudo. Is there a way to configure Python Debugger to use python2.7 or python for python2 as I guess a lot of similar setups will have the same problem? I'm on MacOS High Sierra.

```
$ python2
-bash: /usr/local/bin/python2: No such file or directory

$ which python
/usr/bin/python

$ python
Python 2.7.10 (default, Jul 15 2017, 17:16:57) 
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> 

$ python2.7
Python 2.7.10 (default, Jul 15 2017, 17:16:57) 
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> 

$ sudo ln -s /usr/bin/python /usr/bin/python2
Password:
ln: /usr/bin/python2: Operation not permitted
```


[EDIT]
I've created symlink in /usr/local/bin instead but when I switched language to python2 I get:

```
doesn't want to connect 0 5004
doesn't want to connect 1 5004
doesn't want to connect 2 5004
doesn't want to connect 3 5004
doesn't want to connect 4 5004
doesn't want to connect 5 5004
doesn't want to connect 6 5004
doesn't want to connect 7 5004
doesn't want to connect 8 5004
doesn't want to connect 9 5004
doesn't want to connect 0 5005
doesn't want to connect 1 5005
doesn't want to connect 2 5005
doesn't want to connect 3 5005
doesn't want to connect 4 5005
doesn't want to connect 5 5005
doesn't want to connect 6 5005
doesn't want to connect 7 5005
doesn't want to connect 8 5005
doesn't want to connect 9 5005
fully connected
language: Python2
Traceback (most recent call last):
  File "backends.comm_utils in /Users/***/Library/Application Support/Sublime Text 3/Installed Packages/Python Debugger.sublime-package", line 80, in loop
  File "backends.comm_utils in /Users/***/Library/Application Support/Sublime Text 3/Installed Packages/Python Debugger.sublime-package", line 76, in __call__
  File "backends.comm_utils in /Users/***/Library/Application Support/Sublime Text 3/Installed Packages/Python Debugger.sublime-package", line 66, in __getitem__
ValueError: need more than 1 value to unpack
connection down need more than 1 value to unpack
```

Trying to start debugger results in:
```
Started Debugging
Exception in thread Thread-15:
Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "./python3.3/threading.py", line 1142, in run
  File "mydebugger in /Users/***/Library/Application Support/Sublime Text 3/Installed Packages/Python Debugger.sublime-package", line 48, in <lambda>
  File "backends.dbPython2 in /Users/***/Library/Application Support/Sublime Text 3/Installed Packages/Python Debugger.sublime-package", line 19, in runscript
  File "backends.comm_utils in /Users/***/Library/Application Support/Sublime Text 3/Installed Packages/Python Debugger.sublime-package", line 57, in f
BrokenPipeError: [Errno 32] Broken pipe
```

**Comment by matiasmorant** [comment]
Check if the latest commit solves the problem.
There is a settings file now, where you can set your interpreter

**Comment by Carbon401** [comment]
The latest commit is working fine, thanks
